"""Pydantic schemas for gateway requests and responses.

Organised into domain modules; re-exported here so existing
``from gateway_service.models import X`` imports continue to work.
"""

from gateway_service.models.audio import (
    RawSegment,
    Segment,
    SpeechRequest,
    SpeechResponseFormat,
    TimestampGranularity,
    TranscriptionResponse,
    TranscriptionResponseFormat,
    TranscriptionResult,
    VerboseTranscriptionResponse,
    Voice,
    VoiceListResponse,
    WordTimestamp,
)
from gateway_service.models.chat import (
    ChatAudioConfig,
    ChatCompletionChoice,
    ChatCompletionChunk,
    ChatCompletionChunkChoice,
    ChatCompletionChunkDelta,
    ChatCompletionRequest,
    ChatCompletionResponse,
    ChatCompletionTokenLogprob,
    ChatCompletionTool,
    ChatCompletionToolCall,
    ChatMessage,
    ChoiceLogprobs,
    FunctionCall,
    FunctionDefinition,
    TopLogprob,
)
from gateway_service.models.common import (
    CompletionUsage,
    GatewayHealthResponse,
    HealthResponse,
    ModelListResponse,
    ModelObject,
    ResponseFormat,
    StreamOptions,
)
from gateway_service.models.completions import (
    CompletionChoice,
    CompletionRequest,
    CompletionResponse,
)
from gateway_service.models.embeddings import (
    EmbeddingObject,
    EmbeddingRequest,
    EmbeddingResponse,
    EmbeddingUsage,
)
from gateway_service.models.responses import (
    CreateResponseRequest,
    CreateResponseResponse,
    ResponseOutputContent,
    ResponseOutputMessage,
    ResponseUsage,
)

__all__ = [
    "ChatAudioConfig",
    "ChatCompletionChoice",
    "ChatCompletionChunk",
    "ChatCompletionChunkChoice",
    "ChatCompletionChunkDelta",
    "ChatCompletionRequest",
    "ChatCompletionResponse",
    "ChatCompletionTokenLogprob",
    "ChatCompletionTool",
    "ChatCompletionToolCall",
    "ChatMessage",
    "ChoiceLogprobs",
    "CompletionChoice",
    "CompletionRequest",
    "CompletionResponse",
    "CompletionUsage",
    "CreateResponseRequest",
    "CreateResponseResponse",
    "EmbeddingObject",
    "EmbeddingRequest",
    "EmbeddingResponse",
    "EmbeddingUsage",
    "FunctionCall",
    "FunctionDefinition",
    "GatewayHealthResponse",
    "HealthResponse",
    "ModelListResponse",
    "ModelObject",
    "RawSegment",
    "ResponseFormat",
    "ResponseOutputContent",
    "ResponseOutputMessage",
    "ResponseUsage",
    "Segment",
    "SpeechRequest",
    "SpeechResponseFormat",
    "StreamOptions",
    "TimestampGranularity",
    "TopLogprob",
    "TranscriptionResponse",
    "TranscriptionResponseFormat",
    "TranscriptionResult",
    "VerboseTranscriptionResponse",
    "Voice",
    "VoiceListResponse",
    "WordTimestamp",
]
